name: Welcome New Contributors

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from a new contributor
        id: check_new_contributor
        uses: actions/github-script@v5
        with:
          script: |
            const author = context.payload.pull_request.user.login;
            const { data: commits } = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });
            const authorCommits = commits.filter(commit => commit.author && commit.author.login === author);
            const isNewContributor = authorCommits.length === 0;
            console.log(`Is ${author} a new contributor? ${isNewContributor}`);
            return { isNewContributor }; 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Welcome message
        if: steps.check_new_contributor.outputs.isNewContributor == 'true'
        run: |
          echo "Welcome, @$GITHUB_ACTOR! Thanks for your contribution 🎉"
